builds:
  - id: cpget
    main: ./cmd/cpget/main.go
    binary: cpget
    env:
      - CGO_ENABLED=0
    ldflags: -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: linux
        goarch: arm
        goarm: "7"
      - goos: windows
        goarch: arm
        goarm: "7"

archives:
  - builds:
      - cpget
    name_template: >-
      cpget_
      {{ .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else if eq .Os "linux" }}Linux
      {{- else if eq .Os "windows" }}Windows
      {{- else }}{{ title .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

brews:
  - name: cpget
    repository:
      owner: emaballarin
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/emaballarin/cpget
    description: The fastest file download client
    folder: Formula
    install: |
      bin.install "cpget"
nfpms:
  - license: MIT License
    maintainer: Emanuele Ballarin <emanuele@ballarin.cc>
    homepage: https://github.com/emaballarin/cpget
    bindir: /usr/local/bin
    description: The fastest file download client
    formats:
      - apk
      - deb
      - rpm

checksum:
  name_template: "cpget_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch
